// Get File dialog — modal form for requesting a file upload from a CPE device.
// Generates a URL for the device to upload to, and creates an Upload task.
//
// Attributes:
//   open   - Boolean state signal controlling dialog visibility
//   device - Device object from the parent view

const open = node.attributes.open;
const device = node.attributes.device;

const deviceId = new Signal.Computed(() => device.get()?.["DeviceID.ID"]);
const taskCmd = new Signal.State(null);

// Form state
const fileName = new Signal.State("");
const fileType = new Signal.State("1 Vendor Configuration File");

// File type options per TR-069 spec
const fileTypeOptions = [
  "1 Vendor Configuration File",
  "2 Vendor Log File",
  "3 Vendor Configuration File",
  "4 Vendor Log File",
  "5 Ringer File",
  "6 Tone File",
];

const handleSubmit = () => {
  const name = fileName.get().trim();
  const type = fileType.get();
  const devId = deviceId.get();

  if (!name || !type || !devId) return;

  // Create upload task — URL will be generated by CWMP from FS config
  taskCmd.set({
    name: "upload",
    devices: [devId],
    fileName: name,
    fileType: type,
  });

  // Reset form and close dialog
  fileName.set("");
  fileType.set("1 Vendor Configuration File");
  open.set(false);
};

const handleKeyDown = (e) => {
  if (e.key === "Enter") handleSubmit();
};

// @ts-expect-error: top-level return (script is wrapped in a function at runtime)
return (
  <overlay-dialog open={open}>
    <do-task arg={taskCmd} />
    <h2 class="text-lg font-medium leading-6 text-stone-900 mb-4 pr-6">
      Get file from {deviceId}
    </h2>
    <div class="space-y-4">
      <div>
        <label
          for="get-file-name"
          class="block text-sm font-medium text-stone-700"
        >
          File Name
        </label>
        <input
          id="get-file-name"
          type="text"
          placeholder="e.g. config_backup.xml"
          value={fileName}
          oninput={(e) => fileName.set(e.target.value)}
          onkeydown={handleKeyDown}
          class="mt-1 block w-full shadow-sm focus:ring-cyan-500 focus:border-cyan-500 sm:text-sm border-stone-300 rounded-md px-3 py-2"
        />
      </div>
      <div>
        <label
          for="get-file-type"
          class="block text-sm font-medium text-stone-700"
        >
          File Type
        </label>
        <select
          id="get-file-type"
          value={fileType}
          onchange={(e) => fileType.set(e.target.value)}
          class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-stone-300 focus:outline-none focus:ring-cyan-500 focus:border-cyan-500 sm:text-sm rounded-md"
        >
          {fileTypeOptions.map((t) => (
            <option value={t} selected={fileType.get() === t}>
              {t}
            </option>
          ))}
        </select>
      </div>
      <div class="flex justify-end gap-3 pt-2">
        <button
          onclick={() => {
            fileName.set("");
            fileType.set("1 Vendor Configuration File");
            open.set(false);
          }}
          class="px-4 py-2 border border-stone-300 shadow-sm text-sm font-medium rounded-md text-stone-700 bg-white hover:bg-stone-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500"
        >
          Cancel
        </button>
        <button
          onclick={handleSubmit}
          disabled={() => !fileName.get().trim()}
          class="px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-cyan-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Get File
        </button>
      </div>
    </div>
  </overlay-dialog>
);